// Generated by auto imports
export {};
declare global {
  const AnimationStates: (typeof import("../../utils/constants"))["AnimationStates"];
  const AvatarChildMeshNames: (typeof import("../../utils/constants"))["AvatarChildMeshNames"];
  const TEMP_USER_NAME: (typeof import("../../stores/useChatbotStore"))["TEMP_USER_NAME"];
  const abortNavigation: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["abortNavigation"];
  const acceptHMRUpdate: (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["acceptHMRUpdate"];
  const addRouteMiddleware: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["addRouteMiddleware"];
  const bytesToBase64: (typeof import("../../utils/index"))["bytesToBase64"];
  const callOnce: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/once"))["callOnce"];
  const cancelIdleCallback: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/idle-callback"))["cancelIdleCallback"];
  const clearError: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["clearError"];
  const clearNuxtData: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["clearNuxtData"];
  const clearNuxtState: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/state"))["clearNuxtState"];
  const computed: (typeof import("vue"))["computed"];
  const createError: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["createError"];
  const customRef: (typeof import("vue"))["customRef"];
  const decodeBase64Audio: (typeof import("../../utils/index"))["decodeBase64Audio"];
  const defineAppConfig: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["defineAppConfig"];
  const defineAsyncComponent: (typeof import("vue"))["defineAsyncComponent"];
  const defineComponent: (typeof import("vue"))["defineComponent"];
  const defineNuxtComponent: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/component"))["defineNuxtComponent"];
  const defineNuxtLink: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/components/nuxt-link"))["defineNuxtLink"];
  const defineNuxtPlugin: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["defineNuxtPlugin"];
  const defineNuxtRouteMiddleware: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["defineNuxtRouteMiddleware"];
  const definePageMeta: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/pages/runtime/composables"))["definePageMeta"];
  const definePayloadPlugin: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["definePayloadPlugin"];
  const definePayloadReducer: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["definePayloadReducer"];
  const definePayloadReviver: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["definePayloadReviver"];
  const defineStore: (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["defineStore"];
  const effect: (typeof import("vue"))["effect"];
  const effectScope: (typeof import("vue"))["effectScope"];
  const extendTres: (typeof import("@tresjs/core"))["extend"];
  const extractBindingPosition: (typeof import("@tresjs/cientos"))["extractBindingPosition"];
  const getAppManifest: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/manifest"))["getAppManifest"];
  const getCurrentInstance: (typeof import("vue"))["getCurrentInstance"];
  const getCurrentScope: (typeof import("vue"))["getCurrentScope"];
  const getRouteRules: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/manifest"))["getRouteRules"];
  const h: (typeof import("vue"))["h"];
  const hasInjectionContext: (typeof import("vue"))["hasInjectionContext"];
  const hasSetter: (typeof import("@tresjs/cientos"))["hasSetter"];
  const inject: (typeof import("vue"))["inject"];
  const injectHead: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["injectHead"];
  const isNuxtError: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["isNuxtError"];
  const isPrerendered: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["isPrerendered"];
  const isProxy: (typeof import("vue"))["isProxy"];
  const isReactive: (typeof import("vue"))["isReactive"];
  const isReadonly: (typeof import("vue"))["isReadonly"];
  const isRef: (typeof import("vue"))["isRef"];
  const isShallow: (typeof import("vue"))["isShallow"];
  const isVue2: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/vue-demi"))["isVue2"];
  const isVue3: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/vue-demi"))["isVue3"];
  const loadPayload: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["loadPayload"];
  const markRaw: (typeof import("vue"))["markRaw"];
  const mergeModels: (typeof import("vue"))["mergeModels"];
  const navigateTo: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["navigateTo"];
  const nextTick: (typeof import("vue"))["nextTick"];
  const objToVec3: (typeof import("../../composables/usePos"))["objToVec3"];
  const onActivated: (typeof import("vue"))["onActivated"];
  const onBeforeMount: (typeof import("vue"))["onBeforeMount"];
  const onBeforeRouteLeave: (typeof import("vue-router"))["onBeforeRouteLeave"];
  const onBeforeRouteUpdate: (typeof import("vue-router"))["onBeforeRouteUpdate"];
  const onBeforeUnmount: (typeof import("vue"))["onBeforeUnmount"];
  const onBeforeUpdate: (typeof import("vue"))["onBeforeUpdate"];
  const onDeactivated: (typeof import("vue"))["onDeactivated"];
  const onErrorCaptured: (typeof import("vue"))["onErrorCaptured"];
  const onMounted: (typeof import("vue"))["onMounted"];
  const onNuxtReady: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ready"))["onNuxtReady"];
  const onPrehydrate: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["onPrehydrate"];
  const onRenderTracked: (typeof import("vue"))["onRenderTracked"];
  const onRenderTriggered: (typeof import("vue"))["onRenderTriggered"];
  const onScopeDispose: (typeof import("vue"))["onScopeDispose"];
  const onServerPrefetch: (typeof import("vue"))["onServerPrefetch"];
  const onUnmounted: (typeof import("vue"))["onUnmounted"];
  const onUpdated: (typeof import("vue"))["onUpdated"];
  const pick: (typeof import("@tresjs/cientos"))["pick"];
  const prefetchComponents: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preload"))["prefetchComponents"];
  const preloadComponents: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preload"))["preloadComponents"];
  const preloadPayload: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["preloadPayload"];
  const preloadRouteComponents: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preload"))["preloadRouteComponents"];
  const prerenderRoutes: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["prerenderRoutes"];
  const provide: (typeof import("vue"))["provide"];
  const proxyRefs: (typeof import("vue"))["proxyRefs"];
  const reactive: (typeof import("vue"))["reactive"];
  const readonly: (typeof import("vue"))["readonly"];
  const ref: (typeof import("vue"))["ref"];
  const refreshCookie: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/cookie"))["refreshCookie"];
  const refreshNuxtData: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["refreshNuxtData"];
  const reloadNuxtApp: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/chunk"))["reloadNuxtApp"];
  const requestIdleCallback: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/idle-callback"))["requestIdleCallback"];
  const resetDataLayer: (typeof import("../../utils/index"))["resetDataLayer"];
  const resolveComponent: (typeof import("vue"))["resolveComponent"];
  const setInterval: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/interval"))["setInterval"];
  const setPageLayout: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["setPageLayout"];
  const setResponseStatus: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["setResponseStatus"];
  const shallowReactive: (typeof import("vue"))["shallowReactive"];
  const shallowReadonly: (typeof import("vue"))["shallowReadonly"];
  const shallowRef: (typeof import("vue"))["shallowRef"];
  const showError: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["showError"];
  const storeToRefs: (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["storeToRefs"];
  const testResponseData: (typeof import("../../utils/constants"))["testResponseData"];
  const toRaw: (typeof import("vue"))["toRaw"];
  const toRef: (typeof import("vue"))["toRef"];
  const toRefs: (typeof import("vue"))["toRefs"];
  const toValue: (typeof import("vue"))["toValue"];
  const triggerRef: (typeof import("vue"))["triggerRef"];
  const tryUseNuxtApp: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["tryUseNuxtApp"];
  const unref: (typeof import("vue"))["unref"];
  const updateAppConfig: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/config"))["updateAppConfig"];
  const useAnimations: (typeof import("@tresjs/cientos"))["useAnimations"];
  const useAppConfig: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/config"))["useAppConfig"];
  const useAsyncData: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["useAsyncData"];
  const useAttrs: (typeof import("vue"))["useAttrs"];
  const useAvatarStore: (typeof import("../../stores/useAvatarStore"))["useAvatarStore"];
  const useCamera: (typeof import("@tresjs/core"))["useCamera"];
  const useChatbot: (typeof import("../../composables/useChatbot"))["useChatbot"];
  const useChatbotStore: (typeof import("../../stores/useChatbotStore"))["useChatbotStore"];
  const useCookie: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/cookie"))["useCookie"];
  const useCountdown: (typeof import("../../composables/useCountdown"))["useCountdown"];
  const useCssModule: (typeof import("vue"))["useCssModule"];
  const useCssVars: (typeof import("vue"))["useCssVars"];
  const useEffect: (typeof import("@tresjs/post-processing"))["useEffect"];
  const useEffectPmndrs: (typeof import("@tresjs/post-processing"))["useEffectPmndrs"];
  const useEnvironment: (typeof import("@tresjs/cientos"))["useEnvironment"];
  const useEnvironmentStore: (typeof import("../../stores/useEnvironmentStore"))["useEnvironmentStore"];
  const useError: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["useError"];
  const useFBO: (typeof import("@tresjs/cientos"))["useFBO"];
  const useFBX: (typeof import("@tresjs/cientos"))["useFBX"];
  const useFetch: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/fetch"))["useFetch"];
  const useGLTF: (typeof import("@tresjs/cientos"))["useGLTF"];
  const useGLTFExporter: (typeof import("@tresjs/cientos"))["useGLTFExporter"];
  const useHead: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useHead"];
  const useHeadSafe: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useHeadSafe"];
  const useHydration: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/hydrate"))["useHydration"];
  const useId: (typeof import("vue"))["useId"];
  const useIsMobile: (typeof import("../../composables/isMobile"))["useIsMobile"];
  const useLazyAsyncData: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["useLazyAsyncData"];
  const useLazyFetch: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/fetch"))["useLazyFetch"];
  const useLink: (typeof import("vue-router"))["useLink"];
  const useLoader: (typeof import("@tresjs/core"))["useLoader"];
  const useLoadingIndicator: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/loading-indicator"))["useLoadingIndicator"];
  const useLogger: (typeof import("@tresjs/core"))["useLogger"];
  const useLoop: (typeof import("@tresjs/core"))["useLoop"];
  const useModel: (typeof import("vue"))["useModel"];
  const useNuxtApp: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["useNuxtApp"];
  const useNuxtData: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["useNuxtData"];
  const useNuxtDevTools: (typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.30.1_vite@6.0.7_@types+node@22.10.6_jiti@2.4.2_sass@1.83.1_ters_57oaua3iuxtfr7xidszojia5wm/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools"))["useNuxtDevTools"];
  const usePinia: (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["usePinia"];
  const usePreviewMode: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preview"))["usePreviewMode"];
  const useProgress: (typeof import("@tresjs/cientos"))["useProgress"];
  const useRaycaster: (typeof import("@tresjs/core"))["useRaycaster"];
  const useRenderLoop: (typeof import("@tresjs/core"))["useRenderLoop"];
  const useRenderer: (typeof import("@tresjs/core"))["useRenderer"];
  const useRequestEvent: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestEvent"];
  const useRequestFetch: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestFetch"];
  const useRequestHeader: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestHeader"];
  const useRequestHeaders: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestHeaders"];
  const useRequestURL: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/url"))["useRequestURL"];
  const useResponseHeader: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useResponseHeader"];
  const useRoute: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["useRoute"];
  const useRouteAnnouncer: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/route-announcer"))["useRouteAnnouncer"];
  const useRouter: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["useRouter"];
  const useRuntimeConfig: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["useRuntimeConfig"];
  const useRuntimeHook: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/runtime-hook"))["useRuntimeHook"];
  const useSTT: (typeof import("../../composables/useSTT"))["useSTT"];
  const useScript: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScript"];
  const useScriptClarity: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptClarity"];
  const useScriptCloudflareWebAnalytics: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptCloudflareWebAnalytics"];
  const useScriptCrisp: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptCrisp"];
  const useScriptEventPage: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptEventPage"];
  const useScriptFathomAnalytics: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptFathomAnalytics"];
  const useScriptGoogleAdsense: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleAdsense"];
  const useScriptGoogleAnalytics: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleAnalytics"];
  const useScriptGoogleMaps: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleMaps"];
  const useScriptGoogleTagManager: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleTagManager"];
  const useScriptHotjar: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptHotjar"];
  const useScriptIntercom: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptIntercom"];
  const useScriptLemonSqueezy: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptLemonSqueezy"];
  const useScriptMatomoAnalytics: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptMatomoAnalytics"];
  const useScriptMetaPixel: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptMetaPixel"];
  const useScriptNpm: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptNpm"];
  const useScriptPlausibleAnalytics: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptPlausibleAnalytics"];
  const useScriptSegment: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptSegment"];
  const useScriptStripe: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptStripe"];
  const useScriptTriggerConsent: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptTriggerConsent"];
  const useScriptTriggerElement: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptTriggerElement"];
  const useScriptVimeoPlayer: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptVimeoPlayer"];
  const useScriptXPixel: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptXPixel"];
  const useScriptYouTubePlayer: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptYouTubePlayer"];
  const useSeek: (typeof import("@tresjs/core"))["useSeek"];
  const useSeoMeta: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useSeoMeta"];
  const useServerHead: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useServerHead"];
  const useServerHeadSafe: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useServerHeadSafe"];
  const useServerSeoMeta: (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useServerSeoMeta"];
  const useShadowRoot: (typeof import("vue"))["useShadowRoot"];
  const useSlots: (typeof import("vue"))["useSlots"];
  const useState: (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/state"))["useState"];
  const useSurfaceSampler: (typeof import("@tresjs/cientos"))["useSurfaceSampler"];
  const useTemplateRef: (typeof import("vue"))["useTemplateRef"];
  const useTexture: (typeof import("@tresjs/core"))["useTexture"];
  const useTransitionState: (typeof import("vue"))["useTransitionState"];
  const useTres: (typeof import("@tresjs/core"))["useTres"];
  const useTresContext: (typeof import("@tresjs/core"))["useTresContext"];
  const useTresContextProvider: (typeof import("@tresjs/core"))["useTresContextProvider"];
  const useTresEventManager: (typeof import("@tresjs/core"))["useTresEventManager"];
  const useVideoTexture: (typeof import("@tresjs/cientos"))["useVideoTexture"];
  const watch: (typeof import("vue"))["watch"];
  const watchEffect: (typeof import("vue"))["watchEffect"];
  const watchPostEffect: (typeof import("vue"))["watchPostEffect"];
  const watchSyncEffect: (typeof import("vue"))["watchSyncEffect"];
  const withCtx: (typeof import("vue"))["withCtx"];
  const withDirectives: (typeof import("vue"))["withDirectives"];
  const withKeys: (typeof import("vue"))["withKeys"];
  const withMemo: (typeof import("vue"))["withMemo"];
  const withModifiers: (typeof import("vue"))["withModifiers"];
  const withScopeId: (typeof import("vue"))["withScopeId"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    ComponentPublicInstance,
    ComputedRef,
    DirectiveBinding,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    MaybeRef,
    MaybeRefOrGetter,
    VNode,
    WritableComputedRef,
  } from "vue";
  import("vue");
  // @ts-ignore
  export type { BackendAudioResponse } from "../../utils/index";
  import("../../utils/index");
  // @ts-ignore
  export type { TresObject } from "@tresjs/core";
  import("@tresjs/core");
}
// for vue template auto import
import { UnwrapRef } from "vue";
declare module "vue" {
  interface ComponentCustomProperties {
    readonly AnimationStates: UnwrapRef<
      (typeof import("../../utils/constants"))["AnimationStates"]
    >;
    readonly AvatarChildMeshNames: UnwrapRef<
      (typeof import("../../utils/constants"))["AvatarChildMeshNames"]
    >;
    readonly TEMP_USER_NAME: UnwrapRef<
      (typeof import("../../stores/useChatbotStore"))["TEMP_USER_NAME"]
    >;
    readonly abortNavigation: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["abortNavigation"]
    >;
    readonly acceptHMRUpdate: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["acceptHMRUpdate"]
    >;
    readonly addRouteMiddleware: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["addRouteMiddleware"]
    >;
    readonly bytesToBase64: UnwrapRef<
      (typeof import("../../utils/index"))["bytesToBase64"]
    >;
    readonly callOnce: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/once"))["callOnce"]
    >;
    readonly cancelIdleCallback: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/idle-callback"))["cancelIdleCallback"]
    >;
    readonly clearError: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["clearError"]
    >;
    readonly clearNuxtData: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["clearNuxtData"]
    >;
    readonly clearNuxtState: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/state"))["clearNuxtState"]
    >;
    readonly computed: UnwrapRef<(typeof import("vue"))["computed"]>;
    readonly createError: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["createError"]
    >;
    readonly customRef: UnwrapRef<(typeof import("vue"))["customRef"]>;
    readonly decodeBase64Audio: UnwrapRef<
      (typeof import("../../utils/index"))["decodeBase64Audio"]
    >;
    readonly defineAppConfig: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["defineAppConfig"]
    >;
    readonly defineAsyncComponent: UnwrapRef<
      (typeof import("vue"))["defineAsyncComponent"]
    >;
    readonly defineComponent: UnwrapRef<
      (typeof import("vue"))["defineComponent"]
    >;
    readonly defineNuxtComponent: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/component"))["defineNuxtComponent"]
    >;
    readonly defineNuxtLink: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/components/nuxt-link"))["defineNuxtLink"]
    >;
    readonly defineNuxtPlugin: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["defineNuxtPlugin"]
    >;
    readonly defineNuxtRouteMiddleware: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["defineNuxtRouteMiddleware"]
    >;
    readonly definePageMeta: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/pages/runtime/composables"))["definePageMeta"]
    >;
    readonly definePayloadPlugin: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["definePayloadPlugin"]
    >;
    readonly definePayloadReducer: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["definePayloadReducer"]
    >;
    readonly definePayloadReviver: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["definePayloadReviver"]
    >;
    readonly defineStore: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["defineStore"]
    >;
    readonly effect: UnwrapRef<(typeof import("vue"))["effect"]>;
    readonly effectScope: UnwrapRef<(typeof import("vue"))["effectScope"]>;
    readonly extendTres: UnwrapRef<(typeof import("@tresjs/core"))["extend"]>;
    readonly extractBindingPosition: UnwrapRef<
      (typeof import("@tresjs/cientos"))["extractBindingPosition"]
    >;
    readonly getAppManifest: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/manifest"))["getAppManifest"]
    >;
    readonly getCurrentInstance: UnwrapRef<
      (typeof import("vue"))["getCurrentInstance"]
    >;
    readonly getCurrentScope: UnwrapRef<
      (typeof import("vue"))["getCurrentScope"]
    >;
    readonly getRouteRules: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/manifest"))["getRouteRules"]
    >;
    readonly h: UnwrapRef<(typeof import("vue"))["h"]>;
    readonly hasInjectionContext: UnwrapRef<
      (typeof import("vue"))["hasInjectionContext"]
    >;
    readonly hasSetter: UnwrapRef<
      (typeof import("@tresjs/cientos"))["hasSetter"]
    >;
    readonly inject: UnwrapRef<(typeof import("vue"))["inject"]>;
    readonly injectHead: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["injectHead"]
    >;
    readonly isNuxtError: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["isNuxtError"]
    >;
    readonly isPrerendered: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["isPrerendered"]
    >;
    readonly isProxy: UnwrapRef<(typeof import("vue"))["isProxy"]>;
    readonly isReactive: UnwrapRef<(typeof import("vue"))["isReactive"]>;
    readonly isReadonly: UnwrapRef<(typeof import("vue"))["isReadonly"]>;
    readonly isRef: UnwrapRef<(typeof import("vue"))["isRef"]>;
    readonly isShallow: UnwrapRef<(typeof import("vue"))["isShallow"]>;
    readonly isVue2: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/vue-demi"))["isVue2"]
    >;
    readonly isVue3: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/vue-demi"))["isVue3"]
    >;
    readonly loadPayload: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["loadPayload"]
    >;
    readonly markRaw: UnwrapRef<(typeof import("vue"))["markRaw"]>;
    readonly mergeModels: UnwrapRef<(typeof import("vue"))["mergeModels"]>;
    readonly navigateTo: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["navigateTo"]
    >;
    readonly nextTick: UnwrapRef<(typeof import("vue"))["nextTick"]>;
    readonly objToVec3: UnwrapRef<
      (typeof import("../../composables/usePos"))["objToVec3"]
    >;
    readonly onActivated: UnwrapRef<(typeof import("vue"))["onActivated"]>;
    readonly onBeforeMount: UnwrapRef<(typeof import("vue"))["onBeforeMount"]>;
    readonly onBeforeRouteLeave: UnwrapRef<
      (typeof import("vue-router"))["onBeforeRouteLeave"]
    >;
    readonly onBeforeRouteUpdate: UnwrapRef<
      (typeof import("vue-router"))["onBeforeRouteUpdate"]
    >;
    readonly onBeforeUnmount: UnwrapRef<
      (typeof import("vue"))["onBeforeUnmount"]
    >;
    readonly onBeforeUpdate: UnwrapRef<
      (typeof import("vue"))["onBeforeUpdate"]
    >;
    readonly onDeactivated: UnwrapRef<(typeof import("vue"))["onDeactivated"]>;
    readonly onErrorCaptured: UnwrapRef<
      (typeof import("vue"))["onErrorCaptured"]
    >;
    readonly onMounted: UnwrapRef<(typeof import("vue"))["onMounted"]>;
    readonly onNuxtReady: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ready"))["onNuxtReady"]
    >;
    readonly onPrehydrate: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["onPrehydrate"]
    >;
    readonly onRenderTracked: UnwrapRef<
      (typeof import("vue"))["onRenderTracked"]
    >;
    readonly onRenderTriggered: UnwrapRef<
      (typeof import("vue"))["onRenderTriggered"]
    >;
    readonly onScopeDispose: UnwrapRef<
      (typeof import("vue"))["onScopeDispose"]
    >;
    readonly onServerPrefetch: UnwrapRef<
      (typeof import("vue"))["onServerPrefetch"]
    >;
    readonly onUnmounted: UnwrapRef<(typeof import("vue"))["onUnmounted"]>;
    readonly onUpdated: UnwrapRef<(typeof import("vue"))["onUpdated"]>;
    readonly pick: UnwrapRef<(typeof import("@tresjs/cientos"))["pick"]>;
    readonly prefetchComponents: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preload"))["prefetchComponents"]
    >;
    readonly preloadComponents: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preload"))["preloadComponents"]
    >;
    readonly preloadPayload: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/payload"))["preloadPayload"]
    >;
    readonly preloadRouteComponents: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preload"))["preloadRouteComponents"]
    >;
    readonly prerenderRoutes: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["prerenderRoutes"]
    >;
    readonly provide: UnwrapRef<(typeof import("vue"))["provide"]>;
    readonly proxyRefs: UnwrapRef<(typeof import("vue"))["proxyRefs"]>;
    readonly reactive: UnwrapRef<(typeof import("vue"))["reactive"]>;
    readonly readonly: UnwrapRef<(typeof import("vue"))["readonly"]>;
    readonly ref: UnwrapRef<(typeof import("vue"))["ref"]>;
    readonly refreshCookie: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/cookie"))["refreshCookie"]
    >;
    readonly refreshNuxtData: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["refreshNuxtData"]
    >;
    readonly reloadNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/chunk"))["reloadNuxtApp"]
    >;
    readonly requestIdleCallback: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/idle-callback"))["requestIdleCallback"]
    >;
    readonly resetDataLayer: UnwrapRef<
      (typeof import("../../utils/index"))["resetDataLayer"]
    >;
    readonly resolveComponent: UnwrapRef<
      (typeof import("vue"))["resolveComponent"]
    >;
    readonly setInterval: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/compat/interval"))["setInterval"]
    >;
    readonly setPageLayout: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["setPageLayout"]
    >;
    readonly setResponseStatus: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["setResponseStatus"]
    >;
    readonly shallowReactive: UnwrapRef<
      (typeof import("vue"))["shallowReactive"]
    >;
    readonly shallowReadonly: UnwrapRef<
      (typeof import("vue"))["shallowReadonly"]
    >;
    readonly shallowRef: UnwrapRef<(typeof import("vue"))["shallowRef"]>;
    readonly showError: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["showError"]
    >;
    readonly storeToRefs: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["storeToRefs"]
    >;
    readonly testResponseData: UnwrapRef<
      (typeof import("../../utils/constants"))["testResponseData"]
    >;
    readonly toRaw: UnwrapRef<(typeof import("vue"))["toRaw"]>;
    readonly toRef: UnwrapRef<(typeof import("vue"))["toRef"]>;
    readonly toRefs: UnwrapRef<(typeof import("vue"))["toRefs"]>;
    readonly toValue: UnwrapRef<(typeof import("vue"))["toValue"]>;
    readonly triggerRef: UnwrapRef<(typeof import("vue"))["triggerRef"]>;
    readonly tryUseNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["tryUseNuxtApp"]
    >;
    readonly unref: UnwrapRef<(typeof import("vue"))["unref"]>;
    readonly updateAppConfig: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/config"))["updateAppConfig"]
    >;
    readonly useAnimations: UnwrapRef<
      (typeof import("@tresjs/cientos"))["useAnimations"]
    >;
    readonly useAppConfig: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/config"))["useAppConfig"]
    >;
    readonly useAsyncData: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["useAsyncData"]
    >;
    readonly useAttrs: UnwrapRef<(typeof import("vue"))["useAttrs"]>;
    readonly useAvatarStore: UnwrapRef<
      (typeof import("../../stores/useAvatarStore"))["useAvatarStore"]
    >;
    readonly useCamera: UnwrapRef<(typeof import("@tresjs/core"))["useCamera"]>;
    readonly useChatbot: UnwrapRef<
      (typeof import("../../composables/useChatbot"))["useChatbot"]
    >;
    readonly useChatbotStore: UnwrapRef<
      (typeof import("../../stores/useChatbotStore"))["useChatbotStore"]
    >;
    readonly useCookie: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/cookie"))["useCookie"]
    >;
    readonly useCountdown: UnwrapRef<
      (typeof import("../../composables/useCountdown"))["useCountdown"]
    >;
    readonly useCssModule: UnwrapRef<(typeof import("vue"))["useCssModule"]>;
    readonly useCssVars: UnwrapRef<(typeof import("vue"))["useCssVars"]>;
    readonly useEffect: UnwrapRef<
      (typeof import("@tresjs/post-processing"))["useEffect"]
    >;
    readonly useEffectPmndrs: UnwrapRef<
      (typeof import("@tresjs/post-processing"))["useEffectPmndrs"]
    >;
    readonly useEnvironment: UnwrapRef<
      (typeof import("@tresjs/cientos"))["useEnvironment"]
    >;
    readonly useEnvironmentStore: UnwrapRef<
      (typeof import("../../stores/useEnvironmentStore"))["useEnvironmentStore"]
    >;
    readonly useError: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/error"))["useError"]
    >;
    readonly useFBO: UnwrapRef<(typeof import("@tresjs/cientos"))["useFBO"]>;
    readonly useFBX: UnwrapRef<(typeof import("@tresjs/cientos"))["useFBX"]>;
    readonly useFetch: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/fetch"))["useFetch"]
    >;
    readonly useGLTF: UnwrapRef<(typeof import("@tresjs/cientos"))["useGLTF"]>;
    readonly useGLTFExporter: UnwrapRef<
      (typeof import("@tresjs/cientos"))["useGLTFExporter"]
    >;
    readonly useHead: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useHead"]
    >;
    readonly useHeadSafe: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useHeadSafe"]
    >;
    readonly useHydration: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/hydrate"))["useHydration"]
    >;
    readonly useId: UnwrapRef<(typeof import("vue"))["useId"]>;
    readonly useIsMobile: UnwrapRef<
      (typeof import("../../composables/isMobile"))["useIsMobile"]
    >;
    readonly useLazyAsyncData: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["useLazyAsyncData"]
    >;
    readonly useLazyFetch: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/fetch"))["useLazyFetch"]
    >;
    readonly useLink: UnwrapRef<(typeof import("vue-router"))["useLink"]>;
    readonly useLoader: UnwrapRef<(typeof import("@tresjs/core"))["useLoader"]>;
    readonly useLoadingIndicator: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/loading-indicator"))["useLoadingIndicator"]
    >;
    readonly useLogger: UnwrapRef<(typeof import("@tresjs/core"))["useLogger"]>;
    readonly useLoop: UnwrapRef<(typeof import("@tresjs/core"))["useLoop"]>;
    readonly useModel: UnwrapRef<(typeof import("vue"))["useModel"]>;
    readonly useNuxtApp: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["useNuxtApp"]
    >;
    readonly useNuxtData: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/asyncData"))["useNuxtData"]
    >;
    readonly useNuxtDevTools: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@nuxt+devtools@1.7.0_rollup@4.30.1_vite@6.0.7_@types+node@22.10.6_jiti@2.4.2_sass@1.83.1_ters_57oaua3iuxtfr7xidszojia5wm/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools"))["useNuxtDevTools"]
    >;
    readonly usePinia: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.3.5_pinia@2.3.0_typescript@5.7.3_vue@3.5.13_typescript@5.7.3___rollup@4.30.1/node_modules/@pinia/nuxt/dist/runtime/composables"))["usePinia"]
    >;
    readonly usePreviewMode: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/preview"))["usePreviewMode"]
    >;
    readonly useProgress: UnwrapRef<
      (typeof import("@tresjs/cientos"))["useProgress"]
    >;
    readonly useRaycaster: UnwrapRef<
      (typeof import("@tresjs/core"))["useRaycaster"]
    >;
    readonly useRenderLoop: UnwrapRef<
      (typeof import("@tresjs/core"))["useRenderLoop"]
    >;
    readonly useRenderer: UnwrapRef<
      (typeof import("@tresjs/core"))["useRenderer"]
    >;
    readonly useRequestEvent: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestEvent"]
    >;
    readonly useRequestFetch: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestFetch"]
    >;
    readonly useRequestHeader: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestHeader"]
    >;
    readonly useRequestHeaders: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useRequestHeaders"]
    >;
    readonly useRequestURL: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/url"))["useRequestURL"]
    >;
    readonly useResponseHeader: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/ssr"))["useResponseHeader"]
    >;
    readonly useRoute: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["useRoute"]
    >;
    readonly useRouteAnnouncer: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/route-announcer"))["useRouteAnnouncer"]
    >;
    readonly useRouter: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/router"))["useRouter"]
    >;
    readonly useRuntimeConfig: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/nuxt"))["useRuntimeConfig"]
    >;
    readonly useRuntimeHook: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/runtime-hook"))["useRuntimeHook"]
    >;
    readonly useSTT: UnwrapRef<
      (typeof import("../../composables/useSTT"))["useSTT"]
    >;
    readonly useScript: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScript"]
    >;
    readonly useScriptClarity: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptClarity"]
    >;
    readonly useScriptCloudflareWebAnalytics: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptCloudflareWebAnalytics"]
    >;
    readonly useScriptCrisp: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptCrisp"]
    >;
    readonly useScriptEventPage: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptEventPage"]
    >;
    readonly useScriptFathomAnalytics: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptFathomAnalytics"]
    >;
    readonly useScriptGoogleAdsense: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleAdsense"]
    >;
    readonly useScriptGoogleAnalytics: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleAnalytics"]
    >;
    readonly useScriptGoogleMaps: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleMaps"]
    >;
    readonly useScriptGoogleTagManager: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptGoogleTagManager"]
    >;
    readonly useScriptHotjar: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptHotjar"]
    >;
    readonly useScriptIntercom: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptIntercom"]
    >;
    readonly useScriptLemonSqueezy: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptLemonSqueezy"]
    >;
    readonly useScriptMatomoAnalytics: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptMatomoAnalytics"]
    >;
    readonly useScriptMetaPixel: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptMetaPixel"]
    >;
    readonly useScriptNpm: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptNpm"]
    >;
    readonly useScriptPlausibleAnalytics: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptPlausibleAnalytics"]
    >;
    readonly useScriptSegment: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptSegment"]
    >;
    readonly useScriptStripe: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptStripe"]
    >;
    readonly useScriptTriggerConsent: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptTriggerConsent"]
    >;
    readonly useScriptTriggerElement: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptTriggerElement"]
    >;
    readonly useScriptVimeoPlayer: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptVimeoPlayer"]
    >;
    readonly useScriptXPixel: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptXPixel"]
    >;
    readonly useScriptYouTubePlayer: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/script-stubs"))["useScriptYouTubePlayer"]
    >;
    readonly useSeek: UnwrapRef<(typeof import("@tresjs/core"))["useSeek"]>;
    readonly useSeoMeta: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useSeoMeta"]
    >;
    readonly useServerHead: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useServerHead"]
    >;
    readonly useServerHeadSafe: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useServerHeadSafe"]
    >;
    readonly useServerSeoMeta: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/@unhead+vue@1.11.16_vue@3.5.13_typescript@5.7.3_/node_modules/@unhead/vue"))["useServerSeoMeta"]
    >;
    readonly useShadowRoot: UnwrapRef<(typeof import("vue"))["useShadowRoot"]>;
    readonly useSlots: UnwrapRef<(typeof import("vue"))["useSlots"]>;
    readonly useState: UnwrapRef<
      (typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@22.10.6_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__ior_kh3xpxlje7ewug3wzkeclehluq/node_modules/nuxt/dist/app/composables/state"))["useState"]
    >;
    readonly useSurfaceSampler: UnwrapRef<
      (typeof import("@tresjs/cientos"))["useSurfaceSampler"]
    >;
    readonly useTemplateRef: UnwrapRef<
      (typeof import("vue"))["useTemplateRef"]
    >;
    readonly useTexture: UnwrapRef<
      (typeof import("@tresjs/core"))["useTexture"]
    >;
    readonly useTransitionState: UnwrapRef<
      (typeof import("vue"))["useTransitionState"]
    >;
    readonly useTres: UnwrapRef<(typeof import("@tresjs/core"))["useTres"]>;
    readonly useTresContext: UnwrapRef<
      (typeof import("@tresjs/core"))["useTresContext"]
    >;
    readonly useTresContextProvider: UnwrapRef<
      (typeof import("@tresjs/core"))["useTresContextProvider"]
    >;
    readonly useTresEventManager: UnwrapRef<
      (typeof import("@tresjs/core"))["useTresEventManager"]
    >;
    readonly useVideoTexture: UnwrapRef<
      (typeof import("@tresjs/cientos"))["useVideoTexture"]
    >;
    readonly watch: UnwrapRef<(typeof import("vue"))["watch"]>;
    readonly watchEffect: UnwrapRef<(typeof import("vue"))["watchEffect"]>;
    readonly watchPostEffect: UnwrapRef<
      (typeof import("vue"))["watchPostEffect"]
    >;
    readonly watchSyncEffect: UnwrapRef<
      (typeof import("vue"))["watchSyncEffect"]
    >;
    readonly withCtx: UnwrapRef<(typeof import("vue"))["withCtx"]>;
    readonly withDirectives: UnwrapRef<
      (typeof import("vue"))["withDirectives"]
    >;
    readonly withKeys: UnwrapRef<(typeof import("vue"))["withKeys"]>;
    readonly withMemo: UnwrapRef<(typeof import("vue"))["withMemo"]>;
    readonly withModifiers: UnwrapRef<(typeof import("vue"))["withModifiers"]>;
    readonly withScopeId: UnwrapRef<(typeof import("vue"))["withScopeId"]>;
  }
}
